# Generated by Django 4.2.3 on 2023-07-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name',
            field=models.IntegerField(),
        ),
    ]
