# Generated by Django 4.2.3 on 2023-07-23 13:49

import PlacementFreak.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_batch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, storage=PlacementFreak.storage.UserMediaStorage(), upload_to=''),
        ),
    ]
