# Generated by Django 4.2.3 on 2023-07-27 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='verified',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='experience',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
